# Generated by Django 3.1.2 on 2020-10-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('level', models.CharField(choices=[(0, '暂未评级'), (1, '初级'), (2, '中级'), (2, '高级'), (2, '特级')], default=0, max_length=20, verbose_name='级别')),
                ('image', models.ImageField(null=True, upload_to='teacher/%Y/%m', verbose_name='头像')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
